"""Fix generation agent logic using ShieldLabsAgent."""

import logging
from typing import Any

from crewai import Task, Crew

from app.agents.base import ShieldLabsAgent

logger = logging.getLogger("shieldlabs.agents.fix_generation")


class FixGenerationAgent(ShieldLabsAgent):
    """Agent for generating secure code fixes for security vulnerabilities."""

    def __init__(self, llm: Any = None):
        super().__init__(
            name="Fix Generation Agent",
            role="Security vulnerability remediation specialist",
            goal="Generate safe, secure, and syntax-valid code fixes for identified security findings",
            backstory="You are a senior security engineer with deep expertise in secure coding standards (OWASP, CWE) and code patching.",
            llm=llm,
        )

    def review_fix(self, finding: dict) -> str:
        """
        Runs a real CrewAI task asking the agent to sanity-check a
        fix that was already generated by scanners/fix_generator.py.

        This is a second-opinion review step, not a replacement for
        fix_generator.py's structured JSON output.

        Args:
            finding: a finding dict that already has 'fixed_code' set

        Returns:
            A short plain-text review verdict.
        """
        if self.agent is None:
            logger.warning("CrewAI agent not initialized; skipping fix review.")
            return "Fix review unavailable (CrewAI not initialized)."

        vuln_type = finding.get("vuln_type", "Unknown")
        original = finding.get("code_snippet") or finding.get("vulnerable_code") or ""
        proposed_fix = finding.get("fixed_code") or ""

        task = Task(
            description=(
                "Review this proposed security fix.\n\n"
                "Vulnerability: " + vuln_type + "\n"
                "Original code:\n```\n" + original + "\n```\n\n"
                "Proposed fix:\n```\n" + proposed_fix + "\n```\n\n"
                "In 1-2 sentences, state whether this fix is safe and complete, "
                "or flag any remaining concern."
            ),
            expected_output="A 1-2 sentence verdict on the fix's safety and completeness.",
            agent=self.agent,
        )

        crew = Crew(agents=[self.agent], tasks=[task], verbose=False)
        result = crew.kickoff()
        logger.info("Fix Generation Agent reviewed fix for %s", vuln_type)
        return str(result)